export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
export const ATTEMPT = 'ATTEMPT';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_ATTEMPT = 'CREATE_USER_ATTEMPT';

export const EDIT_USER_ATTEMPT = 'EDIT_USER_ATTEMPT';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
